language: php

services:
    - docker

before_install:
   - ./install-dev.sh
   
script:
   - ./tests.sh
   - docker-compose run app vendor/bin/phpunit
   - docker exec -it pineapple_app php-cs-fixer fix --dry-run
