version: '3.5'

services:
  app:
    container_name: pineapple_app
    build:
      context: .docker/PHP
    volumes:
      - ./:/app
    networks:
      - pineapple-card

  server:
    container_name: pineapple_server
    volumes:
      - ./:/app
    build:
      context: .docker/Nginx
    ports:
      - ${SERVER_PORT}:80
    networks:
      - pineapple-card

  db:
    container_name: pineapple_db
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_EXPOSED_PORT}:3306
    networks:
      - pineapple-card

volumes:
  db_data:

networks:
  pineapple-card: